name: 'Datadog Cloud Resource Tagger GitHub Action'
description: 'Run datadog-cloud-resource-tagger against IaC files as a GitHub Action.'
inputs:
  token:
    description: >
      GitHub token for GitHub API requests.
      Users shouldn't need to set this themselves.
    required: true
    default: ${{ github.token }}
  directory:
    description: 'directory with IaC files to scan'
    default: '.'
    required: false
  providers:
    description: 'comma separated list of providers to scan'
    required: false
  resource_types:
    description: 'comma separated list of resource types to scan (skip all others)'
    required: false
  version:
    description: 'The datadog-cloud-resource-tagger version. Can be `latest` or a full version like `0.5.7`'
    default: latest
    required: false
  tags:
    description: 'The specific list of tags to apply'
    default: "dd_git_org,dd_git_repo,dd_git_file,dd_git_modified_commit,dd_git_resource_lines"
    required: false
  changed_files_only:
    description: 'Only tag files that have been changed in the current PR or branch'
    default: false
    required: false

branding:
  icon: 'shield'
  color: 'purple'

runs:
  using: 'node16'
  main: 'dist/index.js'